name: main

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://cdn.discordapp.com/attachments/818761039432253461/852125185549008926/ngrok.exe -OutFile ngrok.exe
    - name: Copy Ngrok to Windows Directory.
      run: | 
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://cdn.discordapp.com/attachments/852129505518026773/852129549990232064/loop.bat -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: .\ngrok.exe tcp 3389
    - name: Customization...
      run: net user Administrator talezz12!
    - name: Customization2...
      run: net user Administrator /active:yes
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
